version: '3.9'

services:
  ibl:
    container_name: dswiki
    image: jupyter/datascience-notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /Users/tanakatouma/vscode/IBLM/:/home/IBLM/
    command: start-notebook.sh --NotebookApp.token=''